### ISSUE TITLE
how to install pydensecrf for ubuntu?

### ISSUE THREAD

**Issue by SuperDickHead** [liutongkun/ComAD#1]
Nice work, very intriguing. But can u give me some clue on the installation of pydensecrf?

I use pip install pydebsecrf==1.0rc3 end up with error: legacy-install-failure. I then upgrade the setuptools and it seems dont work.

**Comment by liutongkun** [comment]
Thanks for the kind compliments.  We ran this code on Ubuntu 20.04 and did not encounter the issues you mentioned.

Maybe you can try:
pip install cython
then:
pip install git+https://github.com/lucasb-eyer/pydensecrf.git

or you can refer to :
https://www.pythonpool.com/error-legacy-install-failure/

If they don't work, you can try running the code without using CRF by removing the codes of line 119, 120 in "seg_image.py".

#crf_result = dense_crf(img_crf,heatmap_intra)
#heatmap_intra = torch.from_numpy(crf_result)

When not using CRF, the overall intensity of the image will decrease. We recommend lowering the value from '64' to '50' in line 35 of "filter_algorithm.py" to ensure that the background filtering algorithm is not too strict.

Hope it helps.

**Comment by SuperDickHead** [comment]
simply degrade the python version to 3.6.9 and directly use pip install can work. I find the solution in the repo isue of the link you give.Thanks
