### ISSUE TITLE
Versions of Pillow

### ISSUE THREAD

**Issue by MinoruNakamura-Matsuda** [liutongkun/ComAD#2]
I have a question regarding the specified versions of Pillow in the requirements.txt file for setting up the environment. I noticed that there are two versions mentioned, and I'm unsure about which version to use.

**Comment by liutongkun** [comment]
This may be due to some issues caused by 'pipreqs'. We have made modifications to the "requirements.txt"

**Comment by MinoruNakamura-Matsuda** [comment]
Thank you for your prompt response.

**Comment by Shpain** [comment]
Hello, I would like to ask how ComAD is added to DRAEM, is it implemented as a separate branch and finally fuses the two-part exception score?

**Comment by liutongkun** [comment]
> Hello, I would like to ask how ComAD is added to DRAEM, is it implemented as a separate branch and finally fuses the two-part exception score?

Hi

Yes. For all the combinations with existing methods，we implement them as a totally separate branch. We simply add the results without using any additional normalization techniques
