### ISSUE TITLE
Pixel/AUPRO on the MVTec AD

### ISSUE THREAD

**Issue by mjack3** [liutongkun/ComAD#3]
Hello, and congratulations on this amazing job. 

I wonder if you have the pixel-level AUROC and/or AUPRO performances of your method on the MVTec AD. 

Regards

**Comment by liutongkun** [comment]
Thanks for your kind words. We are sorry that ComAD can not achieve pixel-level anomaly detection so we can not evaluate our method using PRO metric. This is a limitation of our work
